### ISSUE TITLE
Full Screen App Problems (Phone)

### ISSUE THREAD

**Issue by Enzoman34** [FIRST-4030/frc-scout-2015#41] opened 2015-02-05 04:38 UTC
For my phone (Doesn't seem to be a problem on the tablet), whenever there is a confirmation (like confirming auto starting location), it exits the page and opens up a new instance of chrome. I have no idea why and it happens every time.

**Comment by terabyte128** [comment] 2015-02-05 05:44
Cannot reproduce on my phone with running as webapp.

**Comment by terabyte128** [comment] 2015-02-13 04:50
closing bc cannot reproduce...

**Closed by terabyte128** 2015-02-13 04:50 UTC
Labels: bug
