### ISSUE TITLE
location awareness

### ISSUE THREAD

**Issue by emorye** [FIRST-4030/frc-scout-2015#59] opened 2015-02-11 04:38 UTC
If the location of the event isn't retained between matches (make it do that) but auto selecting nearest location would be nice. (there are APIs to do this without too much effort)

**Comment by broomweed** [comment] 2015-02-11 06:19
Didn't we consider this last year and decide it was not worth it? @terabyte128 
IIRC the problem is that there isn't really location data for matches already out there, so we would have to compile that all ourselves.
Although, I guess there's sort of city data in that PDF that I got all the event names out of, so if somebody was really committed they could do it. Maybe it's doable now with some sort of fancy LocationField or something.

**Comment by terabyte128** [comment] 2015-02-12 06:22
Yeah it's kind of a pain and is not really worth it. People can type like 3 letters when they login. We are going to implement the blue alliance api to make matches easier to select.

**Closed by terabyte128** 2015-02-12 06:22 UTC
Labels: wontfix
